using EntityGenerator.DatabaseObjects.DataAccessObjects;
using EntityGenerator.DatabaseObjects.DataTransferObjects;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using System;
using System.Collections.Generic;

namespace Tests
{
  public class MockSetupBase
  {
    public static void MockSetup(Mock<IDataAccessObject> dataAccessMock)
    {
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseObjectCount()).Returns(42);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseSchemas()).Returns(GetMockedSchemas);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseTableValueObjects()).Returns(GetMockedTableValueObjects);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseFunctions()).Returns(GetMockedFunctions);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseColumns()).Returns(GetMockedColumns);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseForeignKeys()).Returns(GetMockedForeignKeys);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseCheckConstraints()).Returns(GetMockedCheckConstraints);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseIndices()).Returns(GetMockedIndices);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseTriggers()).Returns(GetMockedTriggers);
      dataAccessMock.As<IDataAccessObject>().Setup(x => x.DatabaseFunctionReturnColumns(It.IsAny<List<FunctionDto>>())).Callback((List<FunctionDto> databaseFunctions) => { ProcessFunctionReturnColumns(databaseFunctions); });
    }

    private static List<SchemaDto> GetMockedSchemas()
    {
      return new List<SchemaDto>()
      {
        new SchemaDto() { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  SchemaId = 5},
        new SchemaDto() { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "dbo", SchemaId = 1 }
      };
    }
    private static List<TableValueObjectDto> GetMockedTableValueObjects()
    {
      return new List<TableValueObjectDto>
      {
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "AllDbTypes", TypeName = "Table", XType = "U"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "ConfigValues", TypeName = "View", XType = "V"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "DomainType", TypeName = "Table", XType = "U"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "DomainValue", TypeName = "Table", XType = "U"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "GetDomainValue", TypeName = "In-lined Table Function", XType = "IF"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "NullableTimeStampType", TypeName = "Table", XType = "U"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "TimeStampType", TypeName = "Table", XType = "U"},
        new TableValueObjectDto { TableId = 1, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  TableValueObjectName = "User", TypeName = "Table", XType = "U"}
      };
    }
    private static List<FunctionDto> GetMockedFunctions()
    {
      return new List<FunctionDto>
      {
        new FunctionDto { FunctionId = 1125579048, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  FunctionName = "CheckDomainType", TypeName = "SQL scalar function", XType = "FN", Parameters = "@dovId bigint, @dovTypId bigint", ReturnType = "bit", FunctionBody = "CREATE FUNCTION[core].[CheckDomainType]  (@dovId bigint, @dovTypId bigint) RETURNS bit AS   BEGIN DECLARE @retBit bit       IF @dovId IS NULL BEGIN RETURN CAST(1 AS bit)     END SELECT @retBit = CAST(Count(0) AS bit) FROM[core].[DomainValue] WHERE[Id] = @dovId AND[TypeId] = @dovTypId     RETURN @retBit  END;"},
        new FunctionDto { FunctionId = 1253579504, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  FunctionName = "GetDomainValue", TypeName = "SQL inline table-valued function", XType = "IF", Parameters = "@id bigint", ReturnType = "", FunctionBody = "CREATE FUNCTION[core].[GetDomainValue](@id BIGINT)  RETURNS TABLE AS RETURN(SELECT[Id]        , [ModifiedDate]        , [ModifiedUser]        , [TypeId]        , [ValueC]        , [ValueN]        , [ValueD]        , [ValueF]        , [DivId]        , [Description]        , [Unit] FROM[core].[DomainValue] WHERE @id IS NULL OR[Id] = @id)"},
        new FunctionDto { FunctionId = 1845581613, DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  FunctionName = "TableValuedFunction", TypeName = "SQL table-valued-function", XType = "TF", Parameters = "@paramInt int, @paramChar5 char", ReturnType = "", FunctionBody = "CREATE FUNCTION[core].[TableValuedFunction](@paramInt int, @paramChar5 char(5))  RETURNS @returntable TABLE(c1 int, c2 char(5))  AS BEGIN    INSERT @returntable    SELECT @paramInt, @paramChar5    RETURN END"},
      };
    }
    private static List<ColumnDto> GetMockedColumns()
    {
      return new List<ColumnDto>
      {
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "int", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BigIntValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BigIntNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BinaryValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "binary", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BinaryNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "binary", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BitValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bit", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "BitNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bit", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "CharValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "char", CharacterMaximumLength = 10, CharacterOctetLength = 10, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "CharNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "char", CharacterMaximumLength = 10, CharacterOctetLength = 10, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "date", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 0},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "date", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 0},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTimeValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 3},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTimeNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 3},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTime2Value", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTime2NullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTimeOffsetValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetimeoffset", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DateTimeOffsetNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetimeoffset", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DecimalValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "decimal", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 18, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "DecimalNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "decimal", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 18, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "FloatValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "float", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 53, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "FloatNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "float", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 53, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "ImageValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "image", CharacterMaximumLength = 2147483647, CharacterOctetLength = 2147483647, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "ImageNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "image", CharacterMaximumLength = 2147483647, CharacterOctetLength = 2147483647, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "IntValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "int", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "IntNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "int", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "MoneyValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "money", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 4, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "MoneyNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "money", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 4, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NCharValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nchar", CharacterMaximumLength = 10, CharacterOctetLength = 20, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NCharNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nchar", CharacterMaximumLength = 10, CharacterOctetLength = 20, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NTextValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "ntext", CharacterMaximumLength = 1073741823, CharacterOctetLength = 2147483646, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NTextNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "ntext", CharacterMaximumLength = 1073741823, CharacterOctetLength = 2147483646, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NumericValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "numeric", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 18, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NumericNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "numeric", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 18, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NVarCharValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 50, CharacterOctetLength = 100, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NVarCharNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 50, CharacterOctetLength = 100, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NVarCharMaxValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "NVarCharMaxNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "RealValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "real", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 24, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "RealNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "real", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 24, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "RowVersionValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "timestamp", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallDateTimeValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "smalldatetime", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 0},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallDateTimeNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "smalldatetime", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 0},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallIntValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "smallint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 5, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallIntNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "smallint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 5, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallMoneyValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "smallmoney", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 4, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "SmallMoneyNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "smallmoney", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 4, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "Sql_VariantValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "sql_variant", CharacterMaximumLength = 0, CharacterOctetLength = 0, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "Sql_VariantNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "sql_variant", CharacterMaximumLength = 0, CharacterOctetLength = 0, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TextValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "text", CharacterMaximumLength = 2147483647, CharacterOctetLength = 2147483647, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TextNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "text", CharacterMaximumLength = 2147483647, CharacterOctetLength = 2147483647, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TimeValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "time", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TimeNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "time", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TinyIntValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "tinyint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 3, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "TinyIntNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "tinyint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 3, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "UniqueIdentifierValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "uniqueidentifier", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "UniqueIdentifierNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "uniqueidentifier", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarBinaryValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "varbinary", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarBinaryNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "varbinary", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarBinaryMaxValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "varbinary", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarBinaryMaxNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "varbinary", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarCharValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "varchar", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarCharNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "varchar", CharacterMaximumLength = 50, CharacterOctetLength = 50, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarCharMaxValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "varchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "VarCharMaxNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "varchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "XmlValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "xml", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "AllDbTypes", ColumnName = "XmlNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "xml", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ModifiedDate", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ModifiedUser", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "TypeId", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ValueC", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 400, CharacterOctetLength = 800, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ValueN", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ValueD", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "ValueF", ColumnDefault = "NULL", IsNullable = "YES", DataType = "float", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 53, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "DivId", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "Description", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 4000, CharacterOctetLength = 8000, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "Unit", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 100, CharacterOctetLength = 200, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "TypeDescription", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "Mode", ColumnDefault = "NULL", IsNullable = "NO", DataType = "char", CharacterMaximumLength = 1, CharacterOctetLength = 1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "StandardId", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "ConfigValues", ColumnName = "Editable", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "ModifiedDate", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "ModifiedUser", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "Type", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 50, CharacterOctetLength = 100, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "Description", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "Mode", ColumnDefault = "('C')", IsNullable = "NO", DataType = "char", CharacterMaximumLength = 1, CharacterOctetLength = 1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "StandardId", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainType", ColumnName = "Editable", ColumnDefault = "((0))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ModifiedDate", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ModifiedUser", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "TypeId", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ValueC", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 400, CharacterOctetLength = 800, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ValueN", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ValueD", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "ValueF", ColumnDefault = "NULL", IsNullable = "YES", DataType = "float", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 53, NumericPrecisionRadix = 2, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "DivId", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = -1, CharacterOctetLength = -1, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "Description", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 4000, CharacterOctetLength = 8000, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "DomainValue", ColumnName = "Unit", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 100, CharacterOctetLength = 200, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "NullableTimeStampType", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "int", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "NullableTimeStampType", ColumnName = "TimeStampNullableValue", ColumnDefault = "NULL", IsNullable = "YES", DataType = "timestamp", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "TimeStampType", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "int", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 10, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "TimeStampType", ColumnName = "TimeStampValue", ColumnDefault = "NULL", IsNullable = "NO", DataType = "timestamp", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "ModifiedDate", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "ModifiedUser", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "Login", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 255, CharacterOctetLength = 510, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "Password", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 255, CharacterOctetLength = 510, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "PasswordSalt", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 255, CharacterOctetLength = 510, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "Email", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 800, CharacterOctetLength = 1600, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "State", ColumnDefault = "((376))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "FailedLoginCount", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "LastLogin", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "LastPasswordChange", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "DomainLogin", ColumnDefault = "('')", IsNullable = "NO", DataType = "nvarchar", CharacterMaximumLength = 60, CharacterOctetLength = 120, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "ConditionsId", ColumnDefault = "((0))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "ConditionsFixed", ColumnDefault = "((0))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "PrivacyPolicyId", ColumnDefault = "((0))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "PrivacyPolicyFixed", ColumnDefault = "((0))", IsNullable = "NO", DataType = "bigint", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = 19, NumericPrecisionRadix = 10, NumericScale = 0, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "PasswordLinkExtension", ColumnDefault = "NULL", IsNullable = "YES", DataType = "uniqueidentifier", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "PasswordDateOfExpiry", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "NewEmail", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", CharacterMaximumLength = 800, CharacterOctetLength = 1600, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "EmailLinkExtension", ColumnDefault = "NULL", IsNullable = "YES", DataType = "uniqueidentifier", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = null},
        new ColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core",  DatabaseObjectName = "User", ColumnName = "EmailDateOfExpiry", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", CharacterMaximumLength = null, CharacterOctetLength = null, NumericPrecision = null, NumericPrecisionRadix = null, NumericScale = null, DatetimePrecision = 7}
      };

    }
    private static List<ForeignKeyDto> GetMockedForeignKeys()
    {
      return new List<ForeignKeyDto>
      {
        new ForeignKeyDto { DatabaseName = "EntityGeneratorTestDatabase", ForeignKeyName = "fk_CoreDomainType_CoreUser_ModifiedUser", SchemaName = "core",  TableName = "DomainType", FieldName = "ModifiedUser", ReferencedSchemaName = "core", ReferencedTableName = "User", ReferencedFieldName = "Id", DeleteStatement = "ALTER TABLE[core].[DomainType]  DROP CONSTRAINT[fk_CoreDomainType_CoreUser_ModifiedUser]", CreateStatement = "ALTER TABLE[core].[DomainType]  WITH NOCHECK ADD CONSTRAINT[fk_CoreDomainType_CoreUser_ModifiedUser] FOREIGN KEY([Id]) REFERENCES[core].[User]([Id])" },
        new ForeignKeyDto { DatabaseName = "EntityGeneratorTestDatabase", ForeignKeyName = "fk_CoreDomainValue_CoreUser_ModifiedUser", SchemaName = "core",  TableName = "DomainValue", FieldName = "ModifiedUser", ReferencedSchemaName = "core", ReferencedTableName = "User", ReferencedFieldName = "Id", DeleteStatement = "ALTER TABLE[core].[DomainValue]  DROP CONSTRAINT[fk_CoreDomainValue_CoreUser_ModifiedUser]", CreateStatement = "ALTER TABLE[core].[DomainValue]  WITH NOCHECK ADD CONSTRAINT[fk_CoreDomainValue_CoreUser_ModifiedUser] FOREIGN KEY([Id]) REFERENCES[core].[User]([Id])" },
        new ForeignKeyDto { DatabaseName = "EntityGeneratorTestDatabase", ForeignKeyName = "fk_CoreDomainValue_CoreDomainType_TypeId", SchemaName = "core",  TableName = "DomainValue", FieldName = "TypeId", ReferencedSchemaName = "core", ReferencedTableName = "DomainType", ReferencedFieldName = "Id", DeleteStatement = "ALTER TABLE[core].[DomainValue]  DROP CONSTRAINT[fk_CoreDomainValue_CoreDomainType_TypeId]", CreateStatement = "ALTER TABLE[core].[DomainValue]  WITH NOCHECK ADD CONSTRAINT[fk_CoreDomainValue_CoreDomainType_TypeId] FOREIGN KEY([Id]) REFERENCES[core].[DomainType]([Id])" },
        new ForeignKeyDto { DatabaseName = "EntityGeneratorTestDatabase", ForeignKeyName = "fk_CoreUser_CoreUser_ModifiedUser", SchemaName = "core",  TableName = "User", FieldName = "ModifiedUser", ReferencedSchemaName = "core", ReferencedTableName = "User", ReferencedFieldName = "Id", DeleteStatement = "ALTER TABLE[core].[User]  DROP CONSTRAINT[fk_CoreUser_CoreUser_ModifiedUser]", CreateStatement = "ALTER TABLE[core].[User]  WITH NOCHECK ADD CONSTRAINT[fk_CoreUser_CoreUser_ModifiedUser] FOREIGN KEY([Id]) REFERENCES[core].[User]([Id])" },
        new ForeignKeyDto { DatabaseName = "EntityGeneratorTestDatabase", ForeignKeyName = "fkUserDomainValuesState", SchemaName = "core",  TableName = "User", FieldName = "State", ReferencedSchemaName = "core", ReferencedTableName = "DomainValue", ReferencedFieldName = "Id", DeleteStatement = "ALTER TABLE[core].[User]  DROP CONSTRAINT[fkUserDomainValuesState]", CreateStatement = "ALTER TABLE[core].[User]  WITH NOCHECK ADD CONSTRAINT[fkUserDomainValuesState] FOREIGN KEY([Id]) REFERENCES[core].[DomainValue]([Id])" }
      };
    }
    private static List<CheckConstraintDto> GetMockedCheckConstraints()
    {
      return new List<CheckConstraintDto>
      {
        new CheckConstraintDto { DatabaseName = "EntityGeneratorTestDatabase", CheckConstraintName = "chkDomainTypeCoreUserState", SchemaName = "core",  TableName = "User", FieldName = "State", Definition = "([core].[CheckDomainType]([State],(63))=(1))", Status = "Active", IsDisabled = true, DeleteStatement = "ALTER TABLE [core].[User] DROP CONSTRAINT [chkDomainTypeCoreUserState]", CreateStatement = "ALTER TABLE[core].[User] WITH CHECK ADD CONSTRAINT[chkDomainTypeCoreUserState] CHECK([core].[CheckDomainType]([State],(63))= (1))" }
      };
    }
    private static List<IndexDto> GetMockedIndices()
    {
      return new List<IndexDto>
      {
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreDomainValue_ModifiedUser", SchemaName = "core",  TableName = "DomainValue", IndexColumns = "ModifiedUser", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreDomainValue_ModifiedUser] ON [core].[DomainValue]", CreateStatement = "CREATE INDEX [ix_coreDomainValue_ModifiedUser] ON [core].[DomainValue] (ModifiedUser)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreDomainValue_TypeId", SchemaName = "core",  TableName = "DomainValue", IndexColumns = "TypeId", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreDomainValue_TypeId] ON [core].[DomainValue]", CreateStatement = "CREATE INDEX [ix_coreDomainValue_TypeId] ON [core].[DomainValue] (TypeId)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreUser_EmailLinkExtension", SchemaName = "core",  TableName = "User", IndexColumns = "EmailLinkExtension", IncludedColumns = "EmailDateOfExpiry, LastLogin", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreUser_EmailLinkExtension] ON [core].[User]", CreateStatement = "CREATE INDEX [ix_coreUser_EmailLinkExtension] ON [core].[User] (EmailLinkExtension) INCLUDE (EmailDateOfExpiry, LastLogin)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreUser_ModifiedUser", SchemaName = "core",  TableName = "User", IndexColumns = "ModifiedUser", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreUser_ModifiedUser] ON [core].[User]", CreateStatement = "CREATE INDEX [ix_coreUser_ModifiedUser] ON [core].[User] (ModifiedUser)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreUser_PasswordLinkExtension", SchemaName = "core",  TableName = "User", IndexColumns = "PasswordLinkExtension, EmailLinkExtension", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreUser_PasswordLinkExtension] ON [core].[User]", CreateStatement = "CREATE INDEX [ix_coreUser_PasswordLinkExtension] ON [core].[User] (PasswordLinkExtension, EmailLinkExtension)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ix_coreUser_State", SchemaName = "core",  TableName = "User", IndexColumns = "State", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Not unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ix_coreUser_State] ON [core].[User]", CreateStatement = "CREATE INDEX [ix_coreUser_State] ON [core].[User] (State)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "PK__AllDbTyp__3214EC073C636105", SchemaName = "core",  TableName = "AllDbTypes", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [PK__AllDbTyp__3214EC073C636105] ON [core].[AllDbTypes]", CreateStatement = "CREATE INDEX [PK__AllDbTyp__3214EC073C636105] ON [core].[AllDbTypes] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "PK__Nullable__3214EC07C3B08FAF", SchemaName = "core",  TableName = "NullableTimeStampType", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [PK__Nullable__3214EC07C3B08FAF] ON [core].[NullableTimeStampType]", CreateStatement = "CREATE INDEX [PK__Nullable__3214EC07C3B08FAF] ON [core].[NullableTimeStampType] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "PK__TimeStam__3214EC07616B20B7", SchemaName = "core",  TableName = "TimeStampType", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [PK__TimeStam__3214EC07616B20B7] ON [core].[TimeStampType]", CreateStatement = "CREATE INDEX [PK__TimeStam__3214EC07616B20B7] ON [core].[TimeStampType] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "pk_CoreDomainType_Id", SchemaName = "core",  TableName = "DomainType", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [pk_CoreDomainType_Id] ON [core].[DomainType]", CreateStatement = "CREATE INDEX [pk_CoreDomainType_Id] ON [core].[DomainType] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "pk_CoreDomainValue_Id", SchemaName = "core",  TableName = "DomainValue", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [pk_CoreDomainValue_Id] ON [core].[DomainValue]", CreateStatement = "CREATE INDEX [pk_CoreDomainValue_Id] ON [core].[DomainValue] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "pk_CoreUser_Id", SchemaName = "core",  TableName = "User", IndexColumns = "Id", IncludedColumns = "", IndexType = "Clustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [pk_CoreUser_Id] ON [core].[User]", CreateStatement = "CREATE INDEX [pk_CoreUser_Id] ON [core].[User] (Id)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "uc_CoreUser_Email", SchemaName = "core",  TableName = "User", IndexColumns = "Email", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [uc_CoreUser_Email] ON [core].[User]", CreateStatement = "CREATE INDEX [uc_CoreUser_Email] ON [core].[User] (Email)" },
        new IndexDto { DatabaseName = "EntityGeneratorTestDatabase", IndexName = "ucUserLogin", SchemaName = "core",  TableName = "User", IndexColumns = "Login", IncludedColumns = "", IndexType = "Nonclustered index", Unique = "Unique", ObjectType = "Table", DeleteStatement = "DROP INDEX [ucUserLogin] ON [core].[User]", CreateStatement = "CREATE INDEX [ucUserLogin] ON [core].[User] (Login)" }
      };
    }
    private static List<TriggerDto> GetMockedTriggers()
    {
      return new List<TriggerDto>
      {
        new TriggerDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", TriggerName = "SampleTrigger", ParentObjectName = "TimeStampType", ParentObjectXtype = "CREATE TRIGGER [SampleTrigger]    ON [core].[TimeStampType]    FOR DELETE, INSERT, UPDATE    AS    BEGIN      SET NOCOUNT ON    END", Definition = "", IsDisabled = false, IsInsteadOfTrigger = false, IsNotForReplication = false, IsMsShipped = false }
      };
    }

    private static void ProcessFunctionReturnColumns(List<FunctionDto> databaseFunctions)
    {
      foreach (FunctionDto function in databaseFunctions)
      {
        if (function.SchemaName.Equals("core", StringComparison.InvariantCultureIgnoreCase) &&
            function.FunctionName.Equals("GetDomainValue", StringComparison.InvariantCultureIgnoreCase))
        {
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "Id", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", MaximumLength = 8, Order = 1 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ModifiedDate", ColumnDefault = "NULL", IsNullable = "NO", DataType = "datetime2", MaximumLength = 8, Order = 2 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ModifiedUser", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", MaximumLength = 8, Order = 3 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "TypeId", ColumnDefault = "NULL", IsNullable = "NO", DataType = "bigint", MaximumLength = 8, Order = 4 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ValueC", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", MaximumLength = 800, Order = 5 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ValueN", ColumnDefault = "NULL", IsNullable = "YES", DataType = "bigint", MaximumLength = 8, Order = 6 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ValueD", ColumnDefault = "NULL", IsNullable = "YES", DataType = "datetime2", MaximumLength = 8, Order = 7 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "ValueF", ColumnDefault = "NULL", IsNullable = "YES", DataType = "float", MaximumLength = 8, Order = 8 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "DivId", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", MaximumLength = -1, Order = 9 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "Description", ColumnDefault = "NULL", IsNullable = "NO", DataType = "nvarchar", MaximumLength = 8000, Order = 10 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "GetDomainValue", ColumnName = "Unit", ColumnDefault = "NULL", IsNullable = "YES", DataType = "nvarchar", MaximumLength = 200, Order = 11 });
        }
        if (function.SchemaName.Equals("core", StringComparison.InvariantCultureIgnoreCase) &&
            function.FunctionName.Equals("TableValuedFunction", StringComparison.InvariantCultureIgnoreCase))
        {
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "TableValuedFunction", ColumnName = "c1", ColumnDefault = "NULL", IsNullable = "YES", DataType = "int", MaximumLength = 4, Order = 1 });
          function.ReturnColumns.Add(new TableValueFunctionReturnColumnDto { DatabaseName = "EntityGeneratorTestDatabase", SchemaName = "core", DatabaseObjectName = "TableValuedFunction", ColumnName = "c2", ColumnDefault = "NULL", IsNullable = "YES", DataType = "char", MaximumLength = 5, Order = 2 });
        }
      }
    }
  }
}