name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore EntityGenerator/EntityGenerator.sln
    - name: Build
      run: dotnet build EntityGenerator/EntityGenerator.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish EntityGenerator/EntityGeneratorCLI/EntityGeneratorCLI.csproj --configuration Release --output /output/src --self-contained
