name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NET_SDK: 6.0.x
      CONFIGURATION: Release
      RUNTIME: win-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{env.NET_SDK}}
    - name: Restore dependencies
      run: dotnet restore EntityGenerator/EntityGenerator.sln
    - name: Build
      run: dotnet build EntityGenerator/EntityGenerator.sln --configuration ${{env.CONFIGURATION}} --no-restore
    - name: Test
      run: dotnet test EntityGenerator/EntityGenerator.sln --no-restore --verbosity normal
